/*!
 * GnuplotEditor
 *
 * Copyright (c) 2022 yuya
 *
 * This software is released under the GPLv3.
 * see https://www.gnu.org/licenses/gpl-3.0.en.html
 */

#ifndef GNUPLOTCOMPLETION_H
#define GNUPLOTCOMPLETION_H
#include <QStringList>
#include <QObject>

namespace gnuplot_cpl
{

inline QStringList mainCmd()
{
    return QStringList() << "break"
                         << "cd"
                         << "call"
                         << "clear"
                         << "continue"
                         << "do"
                         << "evaluate"
                         << "exit"
                         << "fit"
                         << "help"
                         << "history"
                         << "if"
                         << "for"
                         << "import"
                         << "load"
                         << "lower"
                         << "pause"
                         << "plot"
                         << "print"
                         << "printerr"
                         << "pwd"
                         << "quit"
                         << "raise"
                         << "refresh"
                         << "replot"
                         << "reread"
                         << "reset"
                         << "save"
                         << "set"
                         << "show"
                         << "shell"
                         << "splot"
                         << "stats"
                         << "system"
                         << "test"
                         << "toggle"
                         << "undefine"
                         << "unset"
                         << "update"
                         << "terminal";
} //commands

class GnuplotCompletionModel : public QObject
{
    Q_OBJECT
public:
    explicit GnuplotCompletionModel(QObject *parent) : QObject(parent) {}

public slots:
    void setCompletionList(const QString& firstCmd, const QString& preCmd, const int index);
    void setToolTip(const QString& text, const QString& firstCmd, const QString& previousCmd);
    void setParentFolder(const QString& folderPath);

private:
    inline QStringList parameter() { return QStringList() << "ARG1"
                                                          << "ARG2"
                                                          << "ARG3"
                                                          << "ARG4"
                                                          << "ARG5"
                                                          << "ARG6"
                                                          << "ARG7"
                                                          << "ARG8"
                                                          << "ARG9"
                                                          << "ARGC"; }
    inline QStringList expression() { return QStringList() << "abs"
                                                           << "acos"
                                                           << "acosh"
                                                           << "airy"
                                                           << "arg"
                                                           << "asin"
                                                           << "asinh"
                                                           << "atan"
                                                           << "atan2"
                                                           << "atanh"
                                                           << "EllipticK"
                                                           << "EllipticE"
                                                           << "EllipticPi"
                                                           << "besj0"
                                                           << "besy0"
                                                           << "besy1"
                                                           << "ceil"
                                                           << "cos"
                                                           << "cosh"
                                                           << "erf"
                                                           << "erfc"
                                                           << "exp"
                                                           << "expint"
                                                           << "floor"
                                                           << "gamma"
                                                           << "ibeta"
                                                           << "inverf"
                                                           << "igamma"
                                                           << "imag"
                                                           << "invnorm"
                                                           << "int"
                                                           << "lambertw"
                                                           << "lgamma"
                                                           << "log"
                                                           << "log10"
                                                           << "norm"
                                                           << "rand"
                                                           << "real"
                                                           << "sgn"
                                                           << "sin"
                                                           << "sinh"
                                                           << "sqrt"
                                                           << "tan"
                                                           << "tanh"
                                                           << "voigt"
                                                           << "cerf"
                                                           << "cdawson"
                                                           << "faddeeva"
                                                           << "erfi"
                                                           << "VP"
                                                           << "gprintf"
                                                           << "sprintf"
                                                           << "strlen"
                                                           << "strstr"
                                                           << "substr"
                                                           << "strftime"
                                                           << "strptime"
                                                           << "system"
                                                           << "word"
                                                           << "words"
                                                           << "column"
                                                           << "columnhead"
                                                           << "exists"
                                                           << "hsv2rgb"
                                                           << "stringcolumn"
                                                           << "timecolumn"
                                                           << "tm_hour"
                                                           << "tm_mday"
                                                           << "tm_min"
                                                           << "tm_mon"
                                                           << "tm_sec"
                                                           << "tm_wday"
                                                           << "tm_yday"
                                                           << "tm_year"
                                                           << "time"
                                                           << "valid";}
    inline QStringList modifiers() { return QStringList() << "binary"
                                                          << "nonuniform"
                                                          << "matrix"
                                                          << "index"
                                                          << "every"
                                                          << "skip"
                                                          << "using"
                                                          << "smooth"
                                                          << "bins"
                                                          << "volatile"
                                                          << "noautoscale";}
        inline QStringList binary() { return QStringList() << "array="
                                                           << "record="
                                                           << "skip="
                                                           << "format="
                                                           << "endian="
                                                           << "filetype="
                                                           << "scan="
                                                           << "transpose"
                                                           << "dx="
                                                           << "dy="
                                                           << "dz="
                                                           << "flipx"
                                                           << "flipy"
                                                           << "flipz"
                                                           << "origin="
                                                           << "center="
                                                           << "rotate="
                                                           << "perpendicular=";}
            inline QStringList endian() { return QStringList() << "little"
                                                               << "big"
                                                               << "default"
                                                               << "swap"
                                                               << "swab";}
            inline QStringList filetype() { return QStringList() << "avs"
                                                                       << "bin"
                                                                       << "edf"
                                                                       << "ehf"
                                                                       << "gif"
                                                                       << "gpbin"
                                                                       << "jpeg"
                                                                       << "jpg"
                                                                       << "png"
                                                                       << "raw"
                                                                       << "rgb"
                                                                       << "auto";}
        inline QStringList nonuniform() { return QStringList() << "matrix"; }
        inline QStringList smooth() { return QStringList() << "unique"
                                                           << "frequency"
                                                           << "fnormal"
                                                           << "cumulative"
                                                           << "cnormal"
                                                           << "bins"
                                                           << "kdensity"
                                                           << "kdensity bandwidth"
                                                           << "csplines"
                                                           << "acsplines"
                                                           << "mcsplines"
                                                           << "bezier"
                                                           << "sbezier"
                                                           << "unwrap";}
            inline QStringList bandwidth() { return QStringList(); }
    inline QStringList variables() { return QStringList(); }
    inline QStringList helpItems() { return QStringList(); }
    inline QStringList historyCmd() { return QStringList(); }
    inline QStringList style() { return QStringList() << "linestyle" << "ls"
                                                      << "linetype" << "lt"
                                                      << "linewidth" << "lw"
                                                      << "linecolor" << "lc"
                                                      << "pointtype" << "pt"
                                                      << "pointsize" << "ps"
                                                      << "fill" << "fs"
                                                      << "fillcolor" << "fc"
                                                      << "nohidden3d"
                                                      << "nocontours"
                                                      << "nosurface"
                                                      << "palette"
                                                      << "pointinterval" << "pi"
                                                      << "pointnumber" << "pn"
                                                      << "dashtype" << "dt";}
    inline QStringList d2style() { return QStringList() << "boxerrorbars"
                                                        << "boxes"
                                                        << "boxplot"
                                                        << "boxxyerror"
                                                        << "candlesticks"
                                                        << "circles"
                                                        << "ellipses"
                                                        << "dots"
                                                        << "filledcurces"
                                                        << "financebars"
                                                        << "fsteps"
                                                        << "fillsteps"
                                                        << "histeps"
                                                        << "histograms"
                                                        << "image"
                                                        << "impulses"
                                                        << "labels"
                                                        << "lines"
                                                        << "linespoints"
                                                        << "parallelaxes"
                                                        << "points"
                                                        << "steps"
                                                        << "surface"
                                                        << "table"
                                                        << "rgbalpha"
                                                        << "rgbimage"
                                                        << "vectors"
                                                        << "xerrorbars"
                                                        << "xyerrorbars"
                                                        << "yerrorbars"
                                                        << "xerrorlines"
                                                        << "xyerrorlines"
                                                        << "yerrorlines"
                                                        << "zerrorfill";}
    inline QStringList d3style() { return QStringList() << "points"
                                                        << "images"
                                                        << "impulse"
                                                        << "labels"
                                                        << "vector"
                                                        << "pm3d"
                                                        << "coloring"
                                                        << "surfaces"
                                                        << "contours";}
        inline QStringList filledcurves() { return QStringList() << "closed"
                                                                 << "xy="
                                                                 << "above"
                                                                 << "below"
                                                                 << "x1"
                                                                 << "x2"
                                                                 << "y"
                                                                 << "r";}
            inline QStringList closed() { return QStringList() << "above"
                                                               << "below";}
    inline QStringList axes() { return QStringList() << "x1y1" << "x1y2" << "x2y1" << "x2y2"; }
    inline QStringList titleSpec() { return QStringList() << "offset"
                                                          << "font"
                                                          << "textcolor" << "tc"
                                                          << "noenhanced"
                                                          << "enhanced";}
    inline QStringList option() { return QStringList() << "angles"
                                                       << "arrow"
                                                       << "autoscale"
                                                       << "bind"
                                                       << "bmargin"
                                                       << "border"
                                                       << "boxwidth"
                                                       << "color"
                                                       << "colorsequence"
                                                       << "clabel"
                                                       << "clip"
                                                       << "cntrlabel"
                                                       << "cntrparam"
                                                       << "colorbox"
                                                       << "colornames"
                                                       << "contour"
                                                       << "dashtype"
                                                       << "data style"
                                                       << "datafile"
                                                       << "desimalsign"
                                                       << "dgrid3d"
                                                       << "dummy"
                                                       << "encoding"
                                                       << "errorbars"
                                                       << "fit"
                                                       << "fontpath"
                                                       << "format"
                                                       << "function style"
                                                       << "functions"
                                                       << "grid"
                                                       << "hidden3d"
                                                       << "historysize"
                                                       << "history"
                                                       << "isosamples"
                                                       << "jitter"
                                                       << "key"
                                                       << "label"
                                                       << "linetype"
                                                       << "link"
                                                       << "lmargin"
                                                       << "loadpath"
                                                       << "locale"
                                                       << "logscale"
                                                       << "macros"
                                                       << "mapping"
                                                       << "margins"
                                                       << "margin"
                                                       << "micro"
                                                       << "minussign"
                                                       << "monochrome"
                                                       << "mouse"
                                                       << "mttics"
                                                       << "multiplot"
                                                       << "mx2tics"
                                                       << "mxtics"
                                                       << "my2tics"
                                                       << "mytics"
                                                       << "mztics"
                                                       << "nonlinear"
                                                       << "object"
                                                       << "offsets"
                                                       << "origin"
                                                       << "output"
                                                       << "parametric"
                                                       << "paxis"
                                                       << "plot"
                                                       << "pm3d"
                                                       << "palette"
                                                       << "pointintervalbox"
                                                       << "pointsize"
                                                       << "polar"
                                                       << "print"
                                                       << "psdir"
                                                       << "raxis"
                                                       << "rgbmax"
                                                       << "rlabel"
                                                       << "rmargin"
                                                       << "rrange"
                                                       << "rtics"
                                                       << "samples"
                                                       << "size"
                                                       << "style"
                                                       << "surface"
                                                       << "table"
                                                       << "terminal"
                                                       << "termoption"
                                                       << "theta"
                                                       << "tics"
                                                       << "ticslevel"
                                                       << "ticscale"
                                                       << "timestamp"
                                                       << "timefmt"
                                                       << "title"
                                                       << "tmargin"
                                                       << "trange"
                                                       << "ttics"
                                                       << "urange"
                                                       << "variables"
                                                       << "version"
                                                       << "view"
                                                       << "vrange"
                                                       << "x2data"
                                                       << "x2dtics"
                                                       << "x2label"
                                                       << "x2mtics"
                                                       << "x2range"
                                                       << "x2tics"
                                                       << "x2zerozxis"
                                                       << "xdata"
                                                       << "xdtics"
                                                       << "xlabel"
                                                       << "xmtics"
                                                       << "xrange"
                                                       << "xtics"
                                                       << "xyplane"
                                                       << "xzeroaxis"
                                                       << "y2data"
                                                       << "y2dtics"
                                                       << "y2label"
                                                       << "y2mtics"
                                                       << "y2range"
                                                       << "y2tics"
                                                       << "y2zeroaxis"
                                                       << "ydata"
                                                       << "ydtics"
                                                       << "ylabel"
                                                       << "ymtics"
                                                       << "yrange"
                                                       << "ytics"
                                                       << "yzeroaxis"
                                                       << "zdata"
                                                       << "zdtics"
                                                       << "zzeroaxis"
                                                       << "cbdata"
                                                       << "cbdtics"
                                                       << "zero"
                                                       << "zeroaxis"
                                                       << "zlabel"
                                                       << "zmtics"
                                                       << "zrange"
                                                       << "ztics"
                                                       << "cblabel"
                                                       << "cbmtics"
                                                       << "cbrange"
                                                       << "cbtics";}
        inline QStringList angle() { return QStringList() << "degrees" << "radians"; }
        inline QStringList arrow() { return QStringList() << "nohead"
                                                          << "head"
                                                          << "backhead"
                                                          << "heads"
                                                          << "size"
                                                          << "fixed"
                                                          << "filled"
                                                          << "empty"
                                                          << "nofilled"
                                                          << "noborder"
                                                          << "front"
                                                          << "back"
                                                          << "linestyle" << "ls"
                                                          << "linetype" << "lt"
                                                          << "linewidth" << "lw"
                                                          << "linecolor" << "lc"
                                                          << "dashtype" << "dt";}
        inline QStringList autoscale() { return QStringList() << "noextend" << axes(); }
        inline QStringList border() { return QStringList() << "font"
                                                           << "back"
                                                           << "behind"
                                                           << "linestyle" << "ls"
                                                           << "linetype" << "lt"
                                                           << "linewidth" << "lw"
                                                           << "linecolor" << "lc"
                                                           << "dashtype" << "dt"
                                                           << "polar";}
        inline QStringList boxwidth() { return QStringList() << "absolute"
                                                             << "relative"; }
        inline QStringList colorsequence() { return QStringList() << "default"
                                                                  << "classic"
                                                                  << "podo";}
        inline QStringList clip() { return QStringList() << "points" << "one" << "two"; }
        inline QStringList cntrlabel() { return QStringList() << "format"
                                                              << "font"
                                                              << "start"
                                                              << "interval";}
        inline QStringList cntrparam() { return QStringList() << "linear"
                                                              << "cubicspline"
                                                              << "bspline"
                                                              << "points"
                                                              << "order"
                                                              << "levels"
                                                              << "sorted"
                                                              << "firstlinetype";}
            inline QStringList levels() { return QStringList() << "auto"
                                                               << "discrete"
                                                               << "incremental";}
        inline QStringList colorbox() { return QStringList() << "vertical"
                                                             << "horizontal"
                                                             << "noinvert"
                                                             << "invert"
                                                             << "default"
                                                             << "user"
                                                             << "origin x,y"
                                                             << "size x,y"
                                                             << "front"
                                                             << "back"
                                                             << "noborder"
                                                             << "bdefault"
                                                             << "border";}
        inline QStringList contour() { return QStringList() << "base"
                                                            << "surface"
                                                            << "both";}
        inline QStringList datafile() { return QStringList() << "fortran"
                                                             << "nofpe_trap"
                                                             << "missing"
                                                             << "separator"
                                                             << "commentschars"
                                                             << "binary";}
        inline QStringList desimalsign() { return QStringList() << "local"; }
        inline QStringList dgrid3d() { return QStringList() << "splines"
                                                            << "qnorm"
                                                            << "gauss"
                                                            << "cauchy"
                                                            << "exp"
                                                            << "box"
                                                            << "hann"
                                                            << "kdensity";}
        inline QStringList encoding() { return QStringList() << "locale"; }
        inline QStringList errorbars() { return QStringList() << "small"
                                                              << "large"
                                                              << "fullwidth"
                                                              << "front"
                                                              << "back"
                                                              << "line-properties";}
        inline QStringList fit() { return QStringList() << "nolog"
                                                        << "logfile"
                                                        << "noquiet" << "quiet"
                                                        << "noresults" << "results"
                                                        << "nobrief" << "brief"
                                                        << "noverbose" << "verbose"
                                                        << "noerrorvariables" << "errorvariables"
                                                        << "noconvariancevariables" << "convariancevariables"
                                                        << "noerrorscaling" << "errorscaling"
                                                        << "noprescale" << "prescale"
                                                        << "maxiter" << "default"
                                                        << "limit"
                                                        << "limit_abs"
                                                        << "start-lambda"
                                                        << "lambda-factor"
                                                        << "script"
                                                        << "v4" << "v5";}
        inline QStringList format() { return QStringList() << "x"
                                                           << "y"
                                                           << "xy"
                                                           << "x2"
                                                           << "y2"
                                                           << "z"
                                                           << "cb";}
        inline QStringList grid() { return QStringList() << "nomxtics"
                                                         << "nomytics"
                                                         << "nomztics"
                                                         << "nomx2tics"
                                                         << "nomy2tics"
                                                         << "nomrtics"
                                                         << "nomcbtics"
                                                         << "polar"
                                                         << "layerdefault"
                                                         << "front"
                                                         << "back"
                                                         << "novertical"
                                                         << "mxtics"
                                                         << "mytics"
                                                         << "mztics"
                                                         << "mx2tics"
                                                         << "my2tics"
                                                         << "mrtics"
                                                         << "mcbtics"
                                                         << "noxtics"
                                                         << "noytics"
                                                         << "noztics"
                                                         << "nox2tics"
                                                         << "noy2tics"
                                                         << "nortics"
                                                         << "nocbtics"
                                                         << "vertical";}
        inline QStringList hidden3d() { return QStringList() << "default"
                                                             << "front"
                                                             << "back"
                                                             << "offset"
                                                             << "nooffset"
                                                             << "trianglepattern"
                                                             << "undefined"
                                                             << "noundefined"
                                                             << "noaltdiagonal"
                                                             << "altdiagonal"
                                                             << "nobentover"
                                                             << "bentover";}
        inline QStringList history() { return QStringList() << "size"
                                                            << "quiet"
                                                            << "numbers"
                                                            << "full"
                                                            << "trim"
                                                            << "default";}
        inline QStringList jitter() { return QStringList() << "overlap"
                                                           << "spread"
                                                           << "wrap"
                                                           << "swarm"
                                                           << "square"
                                                           << "vertical";}
        inline QStringList key_1() { return QStringList() << "on"
                                                        << "off"
                                                        << "default";}
        inline QStringList key_2() { return QStringList () << "inside"
                                                           << "outside"
                                                           << "fixed"
                                                           << "lmargin"
                                                           << "rmargin"
                                                           << "tmargin"
                                                           << "bmargin"
                                                           << "at"
                                                           << "left"
                                                           << "right"
                                                           << "center"
                                                           << "top"
                                                           << "bottom"
                                                           << "center"
                                                           << "vertical"
                                                           << "horizontal"
                                                           << "Left"
                                                           << "Right"
                                                           << "noenhanced" << "enhanced"
                                                           << "noopaque" << "opaque"
                                                           << "noreverse" << "reverse"
                                                           << "noinvert" << "invert"
                                                           << "samplen"
                                                           << "spacing"
                                                           << "width"
                                                           << "height"
                                                           << "noautotitle"
                                                           << "autotitle"
                                                           << "title"
                                                           << "font"
                                                           << "textcolor"
                                                           << "nobox" << "box"
                                                           << "maxcols"
                                                           << "maxrows";}
            inline QStringList key_title() { return QStringList() << "noenhanced" << "enhanced"
                                                                  << "center"
                                                                  << "left"
                                                                  << "right";}
            inline QStringList key_box() { return QStringList() << "linestyle"
                                                                << "linetype"
                                                                << "linewidth";}
            inline QStringList key_maxrc() { return QStringList() << "auto"; }
        inline QStringList label() { return QStringList() << "at"
                                                              << "left"
                                                              << "center"
                                                              << "right"
                                                              << "norotate" << "rotate"
                                                              << "noenhanced"
                                                              << "front"
                                                              << "back"
                                                              << "textcolor"
                                                              << "point" << "nopoint"
                                                              << "offset"
                                                              << "boxed"
                                                              << "hypertext";}
        inline QStringList link() { return QStringList() << "x2"
                                                         << "y2"
                                                         << "via   inverse";}
        inline QStringList logscale() { return QStringList() << "x"
                                                             << "x2"
                                                             << "y"
                                                             << "y2"
                                                             << "z"
                                                             << "cb"
                                                             << "r";}
        inline QStringList mapping() { return QStringList() << "cartesian"
                                                            << "spherical"
                                                            << "cylindrical";}
        inline QStringList margin() { return QStringList() << "at screen";}
        inline QStringList monochrome() { return QStringList() << "linetype";}
        inline QStringList mouse() { return QStringList() << "doubleclick" << "nodoubleclick"
                                                          << "nozoomcoordinates" << "zoomcoordinates"
                                                          << "zoomfactors"
                                                          << "noruler"
                                                          << "polardistance" << "polardistancedeg" << "polardistancetan" << "nopolardistance"
                                                          << "format"
                                                          << "mouseformat"
                                                          << "nolabels" << "labels"
                                                          << "nozoomjump" << "zoomjump"
                                                          << "noverbose" << "verbose";}
            inline QStringList mouse_ruler() { return QStringList() << "at"; }
        inline QStringList multiplot() { return QStringList() << "title"
                                                              << "layout";}
            inline QStringList multiplot_layout() const { return QStringList() << "rowsfirst"
                                                                           << "columnsfirst"
                                                                           << "downwards"
                                                                           << "upwards"
                                                                           << "scale"
                                                                           << "margins"
                                                                           << "spacing";}
        inline QStringList mxtics() const { return QStringList() << "default"; }
        inline QStringList nolinear() const { return QStringList() << "x2 via   inverse"
                                                                   << "y2 via   inverse";}
        inline QStringList object() const { return QStringList() << "rectangle"
                                                                 << "ellipse"
                                                                 << "polygon"
                                                                 << "front" << "back" << "behind"
                                                                 << "clip" << "noclip"
                                                                 << "fc" << "fillcolor"
                                                                 << "fs"
                                                                 << "default"
                                                                 << "lw" << "linewidth"
                                                                 << "dt" << "dashtype"
                                                                 << "from  to";}
        inline QStringList paxis() const { return QStringList() << "range"
                                                                << "tics"
                                                                << "range"
                                                                << "tics";}
        inline QStringList pm3d() const { return QStringList() << "at"
                                                               << "interpolate"
                                                               << "scansautomatic"
                                                               << "scansforward"
                                                               << "scansbackward"
                                                               << "depthorder"
                                                               << "flush"
                                                               << "ftriangles" << "noftriangles"
                                                               << "clip1in" << "clip4in"
                                                               << "noclipcb" << "clipcb"
                                                               << "corners2color";}
            inline QStringList pm3d_flush() const { return QStringList() << "begin"
                                                                         << "center"
                                                                         << "end";}
            inline QStringList pm3d_corners2color() const { return QStringList() << "mean"
                                                                             << "geomean"
                                                                             << "harmean"
                                                                             << "rms"
                                                                             << "median"
                                                                             << "min"
                                                                             << "max"
                                                                             << "c1"
                                                                             << "c2"
                                                                             << "c3"
                                                                             << "c4";}
        inline QStringList palette() const { return QStringList() << "gray" << "color"
                                                                  << "gamma"
                                                                  << "rgbformulae ,,"
                                                                  << "cubehelix"
                                                                  << "model"
                                                                  << "positive" << "negative"
                                                                  << "nops_allcF" << "ps_allcF"
                                                                  << "maxcolors"
                                                                  << "palette"
                                                                  << "gradient"
                                                                  << "fit2rgbformulae"
                                                                  << "rgbformulae";}
            inline QStringList palette_rgbformulae() const { return QStringList() << "defined"
                                                                                  << "file"
                                                                                  << "functions ,,";}
            inline QStringList palette_cubehelix() const { return QStringList() << "start"
                                                                                << "cycles"
                                                                                << "saturation";}
            inline QStringList palette_model() const { return QStringList() << "RGB"
                                                                            << "HSV"
                                                                            << "CMY"
                                                                            << "XYZ";}
        inline QStringList rgbmax() const { return QStringList() << "1.0" << "255"; }
        inline QStringList size() const { return QStringList() << "nosquare" << "square"
                                                               << "ratio" << "noratio";}
        inline QStringList ostyle() const { return QStringList() << "function"
                                                                 << "data"
                                                                 << "arrow"
                                                                 << "boxplot"
                                                                 << "circle"
                                                                 << "ellipse size"
                                                                 << "fill"
                                                                 << "histogram"
                                                                 << "line"
                                                                 << "rectangle"
                                                                 << "textbox";}
            inline QStringList ostyle_units() const { return QStringList() << "xy" << "xx" << "yy"
                                                                           << "clip" << "noclip";}
            inline QStringList ostyle_textbox() const { return QStringList() << "opaque"
                                                                             << "transparent"
                                                                             << "noborder" << "border"
                                                                             << "fillcolor";}
        inline QStringList surface() const { return QStringList() << "implicit" << "explicit"; }
        inline QStringList table() const { return QStringList() << "append" << "separator"; }
            inline QStringList table_separator() const { return QStringList() << "whitespace"
                                                                              << "tab"
                                                                              << "comma";}
        inline QStringList termoption() const { return QStringList() << "noenhanced" << "enhanced"
                                                                     << "font"
                                                                     << "fontscale"
                                                                     << "linewidth";}
        inline QStringList theta() const { return QStringList() << "right"
                                                                << "top"
                                                                << "left"
                                                                << "bottom"
                                                                << "clockwise"
                                                                << "cw"
                                                                << "counterclockwise"
                                                                << "ccw";}
        inline QStringList tics() const { return QStringList() << "axis"
                                                               << "border"
                                                               << "nomirror" << "mirror"
                                                               << "in" << "out"
                                                               << "front" << "back"
                                                               << "norotate" << "rotate"
                                                               << "offset" << "nooffset"
                                                               << "left" << "right" << "center" << "autojustify"
                                                               << "format"
                                                               << "font"
                                                               << "noenhanced" << "enhanced"
                                                               << "textcolor"
                                                               << "scale";}
            inline QStringList tics_rotate() const { return QStringList() << "by"; }
            inline QStringList tics_scale() const { return QStringList() << " default"; }
        inline QStringList timestamp() const { return QStringList() << "top"
                                                                    << "bottom"
                                                                    << "norotate" << "rotate"
                                                                    << "offset"
                                                                    << "font"
                                                                    << "textcolor";}
        inline QStringList title() const { return QStringList() << "offset"
                                                                << "font"
                                                                << "textcolor" << "tc"
                                                                << "default"
                                                                << "noenhanced" << "enhanced"; }
        inline QStringList view() const { return QStringList() << "map"
                                                               << "noequal" << "equal"
                                                               << "azimuth";}
            inline QStringList view_map() const { return QStringList() << "scale";}
            inline QStringList view_equal() const { return QStringList() << "xy" << "xyz"; }
        inline QStringList xlabel() const { return QStringList() << "offset"
                                                                 << "font"
                                                                 << "textcolor"
                                                                 << "noenhanced" << "enhanced"
                                                                 << "rotate by"
                                                                 << "rotate parallel"
                                                                 << "norotate";}
        inline QStringList xrange() const { return QStringList() << "noreverse" << "reverse"
                                                                 << "nowriteback" << "writeback"
                                                                 << "noextend" << "extend"
                                                                 << "restore";}
        inline QStringList xtics() const { return QStringList() << "axis" << "border"
                                                                << "nomirror" << "mirror"
                                                                << "in" << "out"
                                                                << "scale"
                                                                << "norotate" << "rotate"
                                                                << "offset" << "nooffset"
                                                                << "left" << "right" << "center" << "autojustify"
                                                                << "add"
                                                                << "autofreq"
                                                                << "format"
                                                                << "font"
                                                                << "noenhanced" << "enhanced"
                                                                << "numeric" << "timedata" << "geographic"
                                                                << "nologscale" << "logscale"
                                                                << "rangelimited"
                                                                << "textcolor";}
        inline QStringList xyplane() const { return QStringList() << "at"
                                                                  << "relative";}
    inline QStringList terminal() const { return QStringList() <<"caca"
                                                               <<"cairolatex"
                                                               <<"canvas"
                                                               <<"cgm"
                                                               <<"context"
                                                               <<"domterm"
                                                               <<"dumb"
                                                               <<"dxf"
                                                               <<"eepic"
                                                               <<"emf"
                                                               <<"emtex"
                                                               <<"epscairo"
                                                               <<"epslatex"
                                                               <<"fig"
                                                               <<"gif"
                                                               <<"hpgl"
                                                               <<"jpeg"
                                                               <<"latex"
                                                               <<"lua"
                                                               <<"mf"
                                                               <<"mp"
                                                               <<"pcl5"
                                                               <<"pdfcairo"
                                                               <<"postscript"
                                                               <<"pslatex"
                                                               <<"pstex"
                                                               <<"pstricks"
                                                               <<"qms"
                                                               <<"qt"
                                                               <<"sixelgd"
                                                               <<"svg"
                                                               <<"texdraw"
                                                               <<"tgif"
                                                               <<"tikz"
                                                               <<"tkcanvas"
                                                               <<"tpic"
                                                               <<"unknown"
                                                               <<"windows"
                                                               <<"wxt"
                                                               <<"push"
                                                               <<"pop"; }
        inline QStringList windows() const { return QStringList() << "color" << "monochrome"
                                                                  << "solid" << "dashed"
                                                                  << "rounded" << "butt"
                                                                  << "enhanced" << "noenhanced"
                                                                  << "font"
                                                                  << "fontscale"
                                                                  << "linewidth"
                                                                  << "pointscale"
                                                                  << "background"
                                                                  << "title"
                                                                  << "size" << "wsize"
                                                                  << "position"
                                                                  << "docked"
                                                                  << "layout"
                                                                  << "standalone"
                                                                  << "close"; }
        inline QStringList canvas() const { return QStringList() << "size"
                                                                 << "background"
                                                                 << "font"
                                                                 << "fsize"
                                                                 << "noenhanced" << "enhanced"
                                                                 << "linewidth"
                                                                 << "rounded" << "butt" << "square"
                                                                 << "dashlength"
                                                                 << "standalone" << "standalone mousing"
                                                                 << "name"
                                                                 << "jsdir"
                                                                 << "title";}
        inline QStringList cgm() const { return QStringList() << "color" << "monochrome"
                                                              << "colid" << "dashed"
                                                              << "norotate" << "rotate"
                                                              << "width"
                                                              << "linewidth"
                                                              << "font"
                                                              << "background"
                                                              << "landscape"
                                                              << "portrait"
                                                              << "default";}
        inline QStringList dumb() const { return QStringList() << "size"
                                                               << "nofeed" << "feed"
                                                               << "aspect"
                                                               << "noenhanced" << "enhanced"
                                                               << "mono" << "ansi" << "ansi256" << "ansirgb";}
        inline QStringList caca() const { return QStringList() << "driver"
                                                               << "format"
                                                               << "default"
                                                               << "list"
                                                               << "color"
                                                               << "monochrome"
                                                               << "noinverted" << "inverted"
                                                               << "enhanced" << "noenhanced"
                                                               << "background"
                                                               << "title"
                                                               << "size"
                                                               << "charset";}
            inline QStringList caca_charset() const { return QStringList() << "ascii"
                                                                           << "blocks"
                                                                           << "unicode";}
        inline QStringList emf() const { return QStringList() << "color" << "monochrome"
                                                              << "enhanced" << "enhanced noproportional"
                                                              << "rounded" << "butt"
                                                              << "linewidth"
                                                              << "dashlength"
                                                              << "size"
                                                              << "background"
                                                              << "font"
                                                              << "fontscale";}
        inline QStringList fig() const { return QStringList() << "monochrome" << "color"
                                                              << "small" << "big" << "size"
                                                              << "landscape" << "portrait"
                                                              << "font"
                                                              << "fontsize"
                                                              << "textnormal"
                                                              << "textspecial"
                                                              << "texthidden"
                                                              << "textrigid"
                                                              << "linewidth" << "lw"
                                                              << "multiplier";}
        inline QStringList hpgl() const { return QStringList() << "eject"; }
        inline QStringList png() const { return QStringList() << "noenhanced" << "enhanced"
                                                              << "notransparent" << "transparent"
                                                              << "nointerlace" << "interlace"
                                                              << "notruecolor" << "truecolor"
                                                              << "rounded" << "butt"
                                                              << "linewidth" << "dashlength"
                                                              << "tiny" << "small" << "medium" << "large" << "giant"
                                                              << "font"
                                                              << "fontscale"
                                                              << "size"
                                                              << "nocrop" << "crop"
                                                              << "background";}
        inline QStringList jpeg() const { return QStringList() << "noenhanced" << "enhanced"
                                                               << "nointerlace" << "interlace"
                                                               << "linewidth" << "dashlength"
                                                               << "rounded" << "butt"
                                                               << "tiny" << "small" << "large" << "giant"
                                                               << "font"
                                                               << "fontscale"
                                                               << "size"
                                                               << "nocrop" << "crop"
                                                               << "bakcround";}
        inline QStringList gif() const { return QStringList() << "noenhanced" << "enhanced"
                                                              << "notransparent" << "transparent"
                                                              << "rounded" << "butt"
                                                              << "linewidth"
                                                              << "dashlength"
                                                              << "tiny" << "small" << "medium" << "large" << "giant"
                                                              << "font"
                                                              << "fontscale"
                                                              << "size"
                                                              << "nocrop" << "crop"
                                                              << "animate" << "animate delay"
                                                              << "loop"
                                                              << "nooptimize" << "optimize"
                                                              << "background";}
        inline QStringList sixelgd() const { return QStringList() << "noenhanced" << "enhanced"
                                                                  << "notransparent" << "transparent"
                                                                  << "rounded" << "butt"
                                                                  << "linewidth"
                                                                  << "dashlength"
                                                                  << "tiny" << "small" << "medium" << "large" << "giant"
                                                                  << "font" << "fontscale"
                                                                  << "size"
                                                                  << "nocrop" << "crop"
                                                                  << "animate"
                                                                  << "background";}
        inline QStringList epslatex() const { return QStringList() << "default"
                                                                   << "standalone" << "input"
                                                                   << "oldstyle" << "newstyle"
                                                                   << "level1" << "leveldefault" << "level3"
                                                                   << "color" << "colour" << "monochrome"
                                                                   << "background" << "nobackground"
                                                                   << "dashlength" << "dl"
                                                                   << "linewidth" << "lw"
                                                                   << "pointscale" << "ps"
                                                                   << "rounded" << "butt"
                                                                   << "clip" << "noclip"
                                                                   << "palfunsparam"
                                                                   << "size"
                                                                   << "header" << "noheader"
                                                                   << "blacktext" << "colortext" << "colourtext"
                                                                   << "font"
                                                                   << "fontscale";}
         inline QStringList pslatex() const { return QStringList() << "default"
                                                                  << "rotate" << "norotate"
                                                                  << "oldstyle" << "newstyle"
                                                                  << "auxfile" << "noauxfile"
                                                                  << "level1" << "leveldefault" << "level3"
                                                                  << "color" << "colour" << "monochrome"
                                                                  << "background" << "nobackground"
                                                                  << "dashlength" << "dl"
                                                                  << "linewidth" << "lw"
                                                                  << "pointscale" << "ps"
                                                                  << "rounded" <<" butt"
                                                                  << "clip" << "noclip"
                                                                  << "palfuncparam"
                                                                  << "size";}
        inline QStringList postscript() const { return QStringList() << "default"
                                                                     << "landscape" << "portrait" << "eps"
                                                                     << "enhanced" << "noenhanced"
                                                                     << "defaultplex" << "simplex" << "duplex"
                                                                     << "fontfile add" << "fontfile delete"
                                                                     << "level1" << "leveldefault" << "level3"
                                                                     << "color" << "colour" << "monochrome"
                                                                     << "background" << "nobackground"
                                                                     << "dashlength" << "dl"
                                                                     << "linewidth" << "lw"
                                                                     << "pointscale" << "ps"
                                                                     << "rounded" <<" butt"
                                                                     << "clip" << "noclip"
                                                                     << "palfuncparam"
                                                                     << "size"
                                                                     << "blacktext" << "colortext" << "colourtext"
                                                                     << "font"
                                                                     << "fontscale";}
        inline QStringList svg() const { return QStringList() << "size"
                                                              << "mouse"
                                                              << "standalone" << "jsdir"
                                                              << "name"
                                                              << "font"
                                                              << "noenhanced" << "enhanced"
                                                              << "fontscale"
                                                              << "rounded" << "butt" << "square"
                                                              << "solid" << "dashed"
                                                              << "linewidth"
                                                              << "background";}
        inline QStringList tgif() const { return QStringList() << "portrait" << "landscape" << "default"
                                                               << "monochrome" << "color"
                                                               << "linewidth" << "lw"
                                                               << "solid" << "dashed"
                                                               << "font";}
        inline QStringList tkcanvas() const { return QStringList() << "tcl" << "perl" << "perltkx" << "python" << "ruby" << "rexx"
                                                                   << "standalone" << "input"
                                                                   << "interactive"
                                                                   << "rounded" << "butt"
                                                                   << "nobackground" <<" background"
                                                                   << "norottext" << "rottext"
                                                                   << "size"
                                                                   << "noenhanced" << "enhanced"
                                                                   << "externalimages" <<" pixels"; }
         inline QStringList latex() const { return QStringList() << "default"
                                                                << "courier" << "roman"
                                                                << "size"
                                                                << "rotate"
                                                                << "norotate";}
        inline QStringList eepic() const { return QStringList() << "default"
                                                                << "color" << "dashed"
                                                                << "rotate"
                                                                << "size"
                                                                << "small" << "tiny";}
        inline QStringList pstricks() const { return QStringList() << "hacktext" << "nohacktext"
                                                                   << "unit" << "nounit";}
        inline QStringList mp() const { return QStringList() << "color" << "colour" << "monochrome"
                                                             << "solid" << "dashed"
                                                             << "notex" << "tex" << "latex"
                                                             << "magnification"
                                                             << "psnfss" << "psnfss-version7" << "nopsnfss"
                                                             << "prologues"
                                                             << "a4paper"
                                                             << "amstex";}
        inline QStringList context() const { return QStringList() << "default"
                                                                  << "defaultsize" <<" size"
                                                                  << "input" << "standalone"
                                                                  << "timestamp" << "notimestamp"
                                                                  << "noheader" << "header"
                                                                  << "color" << "colour" << "monochrome"
                                                                  << "rounded" << "mitered" << "beveled"
                                                                  << "round" <<" butt" << "squared"
                                                                  << "dashed" << "solid"
                                                                  << "dashlength" << "dl"
                                                                  << "linewidth" << "lw"
                                                                  << "fontscale"
                                                                  << "mppoints" << "texpoints"
                                                                  << "inlineimages" << "externalimages"
                                                                  << "defaultfont" << "font";}
        inline QStringList wxt() const { return QStringList() << "size" << "position"
                                                              << "background"
                                                              << "noenhanced" << "enhanced"
                                                              << "font" << "fontscale"
                                                              << "title"
                                                              << "linewidth"
                                                              << "dashlength"
                                                              << "nopersist" << "persist"
                                                              << "noraise" << "raise"
                                                              << "noctrl" << "ctrl"
                                                              << "close";}
        inline QStringList cairolatex() const { return QStringList() << "eps" << "pdf"
                                                                     << "standalone" << "input"
                                                                     << "blacktext" << "colortext" << "colourtext"
                                                                     << "header" << "noheader"
                                                                     << "mono" << "color"
                                                                     << "notransparent" << "transparent"
                                                                     << "nocrop" << "crop"
                                                                     << "background"
                                                                     << "font"
                                                                     << "fontscale"
                                                                     << "linewidth"
                                                                     << "rounded" <<" butt" << "square"
                                                                     << "dashlength"
                                                                     << "size";}
        inline QStringList pdfcairo() const { return QStringList() << "noenhanced" << "enhanced"
                                                                   << "mono" <<" color"
                                                                   << "font"
                                                                   << "fontscale"
                                                                   << "linewidth"
                                                                   << "rounded" << "butt" << "square"
                                                                   << "dashlength"
                                                                   << "background"
                                                                   << "size";}
        inline QStringList pngcairo() const { return QStringList() << "noenhanced" << "enhanced"
                                                                   << "mono" << "color"
                                                                   << "notransparent" << "transparent"
                                                                   << "background"
                                                                   << "font"
                                                                   << "fontscale"
                                                                   << "linewidth"
                                                                   << "rounded" << "butt" << "square"
                                                                   << "dashlength"
                                                                   << "pointscale"
                                                                   << "size";}
        inline QStringList qt() const { return QStringList() << "size"
                                                             << "position"
                                                             << "title"
                                                             << "font"
                                                             << "noenhanced" << "enhanced"
                                                             << "linewidth"
                                                             << "dashlength"
                                                             << "nopersist" << "persist"
                                                             << "noraise" << "raise"
                                                             << "noctrl" << "ctrl"
                                                             << "close"
                                                             << "widget";}
    inline QStringList color() { return QStringList() << "grey10"
                                                      << "gray20"
                                                      << "grey20"
                                                      << "gray30"
                                                      << "grey30"
                                                      << "gray40"
                                                      << "grey40"
                                                      << "gray50"
                                                      << "grey50"
                                                      << "gray60"
                                                      << "grey60"
                                                      << "gray70"
                                                      << "grey70"
                                                      << "gray80"
                                                      << "grey80"
                                                      << "gray90"
                                                      << "grey90"
                                                      << "gray100"
                                                      << "grey100"
                                                      << "gray"
                                                      << "grey"
                                                      << "light-gray"
                                                      << "light-grey"
                                                      << "dark-gray"
                                                      << "dark-grey"
                                                      << "red"
                                                      << "light-red"
                                                      << "dark-red"
                                                      << "yellow"
                                                      << "light-yello"
                                                      << "dark-yellow"
                                                      << "green"
                                                      << "light-green"
                                                      << "dark-green"
                                                      << "spring-green"
                                                      << "forest-green"
                                                      << "sea-green"
                                                      << "blue"
                                                      << "light-blue"
                                                      << "dark-blue"
                                                      << "midnight-blue"
                                                      << "navy"
                                                      << "medium-blue"
                                                      << "royalblue"
                                                      << "skyblue"
                                                      << "cyan"
                                                      << "light-cyan"
                                                      << "dark-cyan"
                                                      << "magenta"
                                                      << "light-magenta"
                                                      << "dark-magenta"
                                                      << "turquoise"
                                                      << "light-turquoise"
                                                      << "dark-turquoise"
                                                      << "pink"
                                                      << "light-pink"
                                                      << "dark-pink"
                                                      << "coral"
                                                      << "light-coral"
                                                      << "orange-red"
                                                      << "salmon"
                                                      << "light-salmon"
                                                      << "dark-salmon"
                                                      << "aquamarine"
                                                      << "khaki"
                                                      << "dark-khaki"
                                                      << "goldenrod"
                                                      << "light-goldenrod"
                                                      << "dark-goldenrod"
                                                      << "gold"
                                                      << "beige"
                                                      << "brown"
                                                      << "orange"
                                                      << "dark-orange"
                                                      << "violet"
                                                      << "dark-violet"
                                                      << "plum"
                                                      << "purple"
                                                      << "brack"
                                                      << "rgb"
                                                      << "bgnd"
                                                      << "default";}

private:
    void getFilesRecursively(const QString& parentPath, const QString& folderPath);
    QString toolTipStyle(const QString& formula, const QString& message)
    {
        QString toolTip = formula;
        if(!message.isEmpty()) toolTip += "\n-----\n" + message;

        return toolTip;
    };

private:
    QStringList dirList;
    QStringList fileList;

signals:
    void completionListSet(const QStringList& list);
    void toolTipSet(const QString& text);
};

/* break
 * cd <"DirName">
 * call <"InputFile"> <Parameter1> <Parameter2> ... <Parameter9>
 * clear
 * continue
 * do for [<InterationSpec>] { }                                                                            //
 * eval <"StringExpression">
 * exit
 * exit message <"ErrorMessage">
 * exit status <ErrorCode>
 * fit {<Ranges>} <Expression> <DataFile> {<Modifier>} {unitweights}                via <Var1>{,<Var2>,...}  //modifier
 * fit {<Ranges>} <Expression> <DataFile> {<Modifier>} {{x|xy|z}error}              via <Var1>{,<Var2>,...}  //
 * fit {<Ranges>} <Expression> <DataFile> {<Modifier>} {error <Var1>{,<Var2>,...}}  via <Var1>{,<Var2>,...}  //
 * help <Items>
 * history
 * history {<Count>} <"OutFile"> {append}
 * history ?<"Command">
 * histroy !<"Command">
 * history !<Count>
 * if (<Condition>) { } else if (<Condition>) { else {} }
 * for [<IntVar> = <Start>:<End>{:<Increment>}]
 * for [<StringVar> in "Str1 Str2 ..."]
 * import <FuncName>(x{x,t,z,...}) from <"ObjFile{:<Symbol>}">
 * load <"FileName">
 * lower {<PlotWindowId>}
 * pause <Time> {<"String">}
 * pause mouse {<EndCondition>}{, <EndCondition>} {<"String">}
 * plot {<Ranges>} <Definition> {axes <Axes>} {<TitleSpec>} {with <Style>}
 * plot {<Ranges>} <Function> {axes <Axes>} {<TitleSpec>} {with <Style>}           //sampling-range
 * plot {<Ranges>} <DataSource> {<Modifier>} {axes <Axes>} {<TitleSpec>} {with <Style>}
 * plot {<Ranges>} keyentry {axes <Axes>} {<TitleSpec>} {with <Style>}
 * print <Formula> {, <Formula>, ...}
 * printerr <Formula> {, <Formula>, ...}
 * pwd
 * quit
 * raise {<PlotWindowId>}
 * refresh
 * replot
 * reread
 * reset
 * save {<Command> {<Command>} ...} <"FileName">
 * set <Option>
 * show <Option>
 * shell
 * splot {<Ranges>} <Function> {<TitleSpec>} {with <Style>} {, {definitions} <Function> ...}
 * splot {<Ranges>} <FileName> {<Modifier>} {<TitleSpec>} {with <Style>} {, {definitions} <Function> ...} //<Modifier>
 * splot {<Ranges>} <DataBolockName> {<Modifier>} {<TitleSpec>} {with <Style>} {, {definitions} <Function> ...}
 * splot {<Ranges>} keyentry {<TitleSpec>} {with <Style>} {, {definitions} <Function> ...}
 * stats {<Ranges>} <"FileName"> {matrix} {name <Prefix>} {{no}output}  //
 * stats {<Ranges>} <"FileName"> {using <Range>} {name <Prefix>} {{no}output}
 * system <"Command">
 * test <TestType>
 * toggle <PlotNo>
 * toggle <"Title">
 * toggle all
 * undefine <Variable>
 * undefine <StrExpression>
 * unset <Option>
 * update <"FileName"> {<"FileName">}
 * while (<Expression>) { }
 */



enum class CommandType
{
    MainCmd,
    DirName,
    InputFileName,    //存在するファイル名
    Parameter,
    InterationSpec,
    Condition,        //文字式による条件
    Message,          //文字式によるメッセージ
    Int,
    Ranges,           //[]やforによる範囲指定
    Expresstion,      //数式
    Variable,         //変数
    HelpItem,         //helpコマンドの項目
    OutFileName,      //出力ファイル名
    HistoryCommand,   //過去のコマンド
    Definition,
    Axes,
    TitleSpec,
    Style,            //with
    Option,
    DataBlockName,
    StatsType,
    TestType,
    PlotNo,
};

}
#endif // GNUPLOTCOMPLETION_H
